# Generated by Django 5.0.3 on 2024-03-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randomforestclassifier',
            old_name='name',
            new_name='user',
        ),
    ]
