# Generated by Django 5.0.3 on 2024-03-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_randomforestclassifier_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaboostclassifier',
            name='name',
        ),
        migrations.RemoveField(
            model_name='decisiontreeclassifier',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gradientboostclassifier',
            name='name',
        ),
        migrations.RemoveField(
            model_name='randomforestclassifier',
            name='user',
        ),
        migrations.AddField(
            model_name='adaboostclassifier',
            name='username',
            field=models.CharField(default='anonimo', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisiontreeclassifier',
            name='username',
            field=models.CharField(default='anonimo', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradientboostclassifier',
            name='username',
            field=models.CharField(default='anonimo', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='randomforestclassifier',
            name='username',
            field=models.CharField(default='anonimo', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
