# Generated by Django 5.0.3 on 2024-03-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_adaboostclassifier_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationresults',
            name='score',
        ),
        migrations.RemoveField(
            model_name='classificationresults',
            name='user',
        ),
        migrations.AddField(
            model_name='classificationresults',
            name='algorithm',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='classificationresults',
            name='username',
            field=models.CharField(default='Desconocido', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
