# Generated by Django 5.0.3 on 2024-03-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_classificationresults_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationresults',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
